
package com.bootcampjava.electricityservice.client.soap.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UtilityPlanServiceImplService", targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", wsdlLocation = "http://localhost:7001/txuenergy/soap?wsdl")
public class UtilityPlanServiceImplService
    extends Service
{

    private final static URL UTILITYPLANSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UTILITYPLANSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName UTILITYPLANSERVICEIMPLSERVICE_QNAME = new QName("http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", "UtilityPlanServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/txuenergy/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTILITYPLANSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        UTILITYPLANSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UtilityPlanServiceImplService() {
        super(__getWsdlLocation(), UTILITYPLANSERVICEIMPLSERVICE_QNAME);
    }

    public UtilityPlanServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTILITYPLANSERVICEIMPLSERVICE_QNAME, features);
    }

    public UtilityPlanServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, UTILITYPLANSERVICEIMPLSERVICE_QNAME);
    }

    public UtilityPlanServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTILITYPLANSERVICEIMPLSERVICE_QNAME, features);
    }

    public UtilityPlanServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityPlanServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort() {
        return super.getPort(new QName("http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", "UtilityPlanServiceImplPort"), UtilityPlanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", "UtilityPlanServiceImplPort"), UtilityPlanService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTILITYPLANSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw UTILITYPLANSERVICEIMPLSERVICE_EXCEPTION;
        }
        return UTILITYPLANSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
