
package com.bootcampjava.electricityservice.client.soap.wsimport;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtilityPlanService", targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilityPlanService {


    /**
     * 
     * @return
     *     returns java.util.List<com.bootcampjava.electricityservice.client.soap.wsimport.ServicePlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServicePlan", targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", className = "com.bootcampjava.electricityservice.client.soap.wsimport.GetServicePlan")
    @ResponseWrapper(localName = "getServicePlanResponse", targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", className = "com.bootcampjava.electricityservice.client.soap.wsimport.GetServicePlanResponse")
    @Action(input = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/UtilityPlanService/getServicePlanRequest", output = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/UtilityPlanService/getServicePlanResponse")
    public List<ServicePlan> getServicePlan();

}
