
package com.reliant.electricityservice.client.soap.mavimport;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Tue Aug 16 23:51:52 CDT 2016
 * Generated source version: 2.2.9
 * 
 */

public final class UtilityPlanService_UtilityPlanServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", "UtilityPlanServiceImplService");

    private UtilityPlanService_UtilityPlanServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = UtilityPlanServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UtilityPlanServiceImplService ss = new UtilityPlanServiceImplService(wsdlURL, SERVICE_NAME);
        UtilityPlanService port = ss.getUtilityPlanServiceImplPort();  
        
        {
        System.out.println("Invoking getServicePlan...");
        java.util.List<com.reliant.electricityservice.client.soap.mavimport.ServicePlan> _getServicePlan__return = port.getServicePlan();
        System.out.println("getServicePlan.result=" + _getServicePlan__return);


        }

        System.exit(0);
    }

}
