
/*
 * 
 */

package com.reliant.electricityservice.client.soap.mavimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 17 10:28:47 CDT 2016
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "UtilityPlanServiceImplService", 
                  wsdlLocation = "file:/C:/BCJMay16/Developer/MIddleLayer/Workspace/java/springworkspace/reliantService/ReliantService/src/main/resources/wsdl/txuenergy.wsdl",
                  targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/") 
public class UtilityPlanServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", "UtilityPlanServiceImplService");
    public final static QName UtilityPlanServiceImplPort = new QName("http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", "UtilityPlanServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/BCJMay16/Developer/MIddleLayer/Workspace/java/springworkspace/reliantService/ReliantService/src/main/resources/wsdl/txuenergy.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/BCJMay16/Developer/MIddleLayer/Workspace/java/springworkspace/reliantService/ReliantService/src/main/resources/wsdl/txuenergy.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UtilityPlanServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UtilityPlanServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityPlanServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UtilityPlanServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public UtilityPlanServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UtilityPlanServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort() {
        return super.getPort(UtilityPlanServiceImplPort, UtilityPlanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UtilityPlanServiceImplPort, UtilityPlanService.class, features);
    }

}
