package com.reliant.electricityservice.client.soap.mavimport;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Aug 17 23:08:56 CDT 2016
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", name = "UtilityPlanService")
@XmlSeeAlso({ObjectFactory.class})
public interface UtilityPlanService {

    @WebMethod
    @Action(input = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/UtilityPlanService/getServicePlanRequest", output = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/UtilityPlanService/getServicePlanResponse")
    @RequestWrapper(localName = "getServicePlan", targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", className = "com.reliant.electricityservice.client.soap.mavimport.GetServicePlan")
    @ResponseWrapper(localName = "getServicePlanResponse", targetNamespace = "http://soapserv.service.soaputilplan.customerutilityws.txuenergy.com/", className = "com.reliant.electricityservice.client.soap.mavimport.GetServicePlanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.reliant.electricityservice.client.soap.mavimport.ServicePlan> getServicePlan();
}
